### ISSUE TITLE
implement Ansible like watchdog

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvlabox/deployment#58]
Type: **feature**

# Feature

Add an additional optional mechanism through which we can monitor the state of the NuvlaBox from outside Docker/Kubernetes. 

The goal is to increase the NB reliability by ensuring we can always understand and repair a broken NB instance due to an upper layer tooling error (like a Docker malfunction that breaks the NB containers).

# Proposed solution

Suggest the introduction of Ansible (in pull mode) as cronjob watchdog to supervise the whole NB system from outside the container runtime engine.

# Requirements

 - the watchdog must be optional
 - there should be a default base playbook, common for all NBs, and publicly available for `pull` from Nuvla
 - upon NB creation, a playbook shall be associated with that NB, and it can be downloaded via a NB-specifc URL
 - the NBE (agent) should be aware that the edge device has the watchdog capability
 - the watchdog updates the respective NB status in case of issues
 - watchdog reports and potential solutions shall be provided via the UI

# Tasks

 - [x] investigate and document the procedure to install and setup ansible pull (https://github.com/nuvlabox/nuvlabox/issues/29)
 - [x] design required workflow for supporting the watchdog (https://github.com/nuvlabox/nuvlabox/issues/30)
 - [x] write base playbook for overall NB status monitoring (https://github.com/nuvlabox/deployment/issues/57)
 - [x] change the agent to add watchdog capability (https://github.com/nuvlabox/agent/issues/76)
 - [x] change the NB status schema and add new nuvlabox-watchdog to cache the base playbook for each nb (https://github.com/nuvla/api-server/issues/500)
 - [x] add watchdog option to NB creation modal (https://github.com/nuvla/ui/issues/648)
 - [x] extend the UI to display watchdog results and allow baremetal actions (https://github.com/nuvla/ui/issues/647)
 - [x] https://github.com/nuvla/documentation/pull/72

**Comment by cjdcordeiro** [comment]
this watchdog mechanism is now called "host-level management" and it is not based on Ansible anymore. Instead, it offers pure shell scripting cronjob tasks. The implementation details can be found at https://github.com/SixSq/tasklist/issues/1954
